---
title: "br_explore_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
```

Reading in the survey, filtering only for Mexico
```{r, include=FALSE}
master_surv_resp <- read_csv("master_survey_resp.csv")
```

```{r}
colnames(master_surv_resp)
surv_mx<- master_surv_resp %>% 
  filter(country=="MEX")
```

Investigating target species distribution by community
```{r, include=FALSE}
#select relevant data and convert to long form 
ts_mx<-surv_mx %>% 
  select(community, 67:69) %>% 
  gather(key = target_number, value = species, -community) %>% 
  filter(!is.na(species)) %>% 
  mutate(target_number = factor(target_number))


#PSC
psc_ts<-ts_mx %>% 
  filter(community=="PSC") %>% 
  group_by(target_number) %>% 
  count(species)

unique(psc_ts$species) #23 different species named in psc

#Altata
alt_ts<-ts_mx %>% 
  filter(community=="ALT") %>% 
  group_by(target_number)

unique(alt_ts$species) #13 different species named in psc

#Tetuan
ttn_ts<-ts_mx %>% 
  filter(community=="TTN") %>% 
  group_by(target_number)

unique(ttn_ts$species) #6 different species named in psc



unique(ts_mx$species)
```
#exploring phase 1
```{r}

master_survey_resp <- read_csv("master_survey_resp.csv")
version_to_package <- read_csv("version_to_package.csv")
packages <- read_csv("packages.csv")


version1<-version_to_package %>% 
  filter(package<=16) %>% 
  left_join(packages)

survey_ce1<-master_survey_resp %>% 
  select(survey_id, survey_version, choice) %>% 
  mutate(RES = ifelse(choice == 1, 1, 0)) %>% 
  merge(version1, all = TRUE) %>% 
  arrange(survey_id) %>% 
  mutate(STR=c(1:205)) 


version2<-version_to_package %>% 
  filter(package>=17)%>% 
  left_join(packages)

survey_ce2<-master_survey_resp %>% 
  select(survey_id, survey_version, choice) %>% 
  mutate(RES = ifelse(choice == 2, 1, 0)) %>% 
  merge(version2, all = TRUE)%>% 
  arrange(survey_id) %>% 
  mutate(STR=c(1:205)) 

survey_ce_total <- rbind(survey_ce1, survey_ce2)

survey_ce<-survey_ce_total %>% 
  mutate(ASC=1) %>% 
  select(STR,RES, ASC, 6:8) %>% 
  mutate(STR=STR*1000+1) %>% 
  arrange(STR) 
  
```

```{r}
library(survival)

clogout1<-clogit(RES~sos+info+own+strata(STR), data=survey_ce)
clogout1
#the own category may have to be organized differently, since there is no order to how the categories are divided. 
```
```{r}
pt2_response<-master_survey_resp %>% 
  select(survey_id, package_nopackage)

pt2_join<-survey_ce_total %>% 
  filter(RES==1) %>% 
  mutate(STR=STR*1000+2) %>% 
  select(STR, sos,info,own,survey_version,package, survey_id) %>% 
  left_join(pt2_response) %>%
  mutate(RES=package_nopackage) %>% 
  select(-package_nopackage)
  
  
pt2_package<-pt2_join %>% 
  mutate(ASC=1)
  
pt2_nopackage<-pt2_join %>% 
  mutate(sos=0, info=0, own=0, ASC=0) %>% 
  mutate(RES = ifelse(RES == 1, 0, 1))

survey_ce_pt2_total<-rbind(pt2_package, pt2_nopackage)

survey_ce_pt2<-survey_ce_pt2_total %>% 
  select(STR,RES, ASC, sos,info,own) %>% 
  arrange(STR)

ce_total<-rbind(survey_ce, survey_ce_pt2)
```

```{r}
clogout2<-clogit(RES~ASC+sos+info+own+strata(STR), data=ce_total)
clogout2$loglik
clogout2

```

## Willingness to Pay/Recieve
#Gage work

```{r, include = FALSE}
master_survey_resp <- read_csv("master_survey_resp.csv")
version_to_package <- read_csv("version_to_package.csv")
packages <- read_csv("packages.csv")
```

#Consolidating wtp/wtr into onc column 
```{r, include = FALSE}
bidding_game<-master_survey_resp %>% 
  select(survey_id, country, survey_version, package_nopackage, choice, wtp_1, wtp_2, wtp_3, wtp_4, wtr_1, wtr_2, wtr_3, wtr_4) %>%
  mutate(wtp = ifelse(wtp_1 == "n", 0,
                         ifelse(wtp_2=="n", 5,
                                ifelse(wtp_3=="n", 10,
                                       ifelse(wtp_4 =="n", 15,
                                              ifelse(wtp_4 =="y", 20, 20)))))) %>% 
  #I messed up and there is one that is yes instead of y   
  mutate(wtr= ifelse(wtr_1=="y", -5,
                        ifelse(wtr_2=="y", -10,
                               ifelse(wtr_3=="y", -15,
                                      ifelse(wtr_4=="y", -20,
                                             ifelse(wtr_4=="n",-25)))))) %>% 
  mutate(amount=ifelse(is.na(wtp),wtr,wtp)) %>% 
  select(survey_id, country, survey_version, choice, package_nopackage, amount)

```

```{r}
ggplot(data = bg_v2p, aes(x=as.factor(package), y = amount)) +
  geom_jitter(position = position_jitter(0.2), color = "darkgray") +
  geom_pointrange(aes(ymin = amount - sd, ymax = amount + sd), data =bgplot_sum)+
  scale_x_discrete(limits = c(1:32))
```
#prepping data for wtp/wtr data viz
```{r}
packages_2 <- packages %>%
  filter(package >16)%>% 
  mutate(survey_version=1:16)

packages_1 <- packages %>%
  filter(package <17) %>% 
  mutate(survey_version=1:16)

packages_join <- inner_join(packages_1, packages_2, by = c("info", "sos", "own"))

pack_join<-packages_join %>% 
  mutate(package=letters[1:16])

#rename(new variable name = existing variable name)

packages_1_comp<-pack_join %>% 
  select(survey_version.x, package.x, package, sos, info, own) %>%
  mutate(choice=1) %>% 
  rename(survey_version=survey_version.x, package_num=package.x)

packages_2_comp<-pack_join %>% 
  select(survey_version.y, package.y, package, sos, info, own) %>%
  mutate(choice=2) %>% 
  rename(survey_version=survey_version.y, package_num=package.y)

packages_comp <- rbind(packages_1_comp, packages_2_comp)
```

#assigning packages to bidding game
```{r}
package_df<-packages_comp %>% 
#  select(survey_version, choice, package) %>% 
  left_join(bidding_game, by = c('survey_version', 'choice')) %>% 
  mutate(package=as.factor(package)) %>% 
  mutate(sos=as.factor(sos)) %>% 
  mutate(own=as.factor(own)) %>% 
  mutate(survey_version=as.factor(survey_version)) %>% 
  mutate(choice=as.factor(choice)) %>% 
  na.omit()
```

```{r}
ggplot(package_df, aes(x=package, y=amount)) +
  geom_dotplot(binaxis = "y", 
               stackdir = "center", 
               position = "dodge",
               dotsize=0.8,
               aes(fill = own,
                   colour = own,
                   shape = sos)
               #binpositions="all",
               #trim=FALSE
               )
```

```{r}
ggplot(package_df, aes(x=package, y=amount)) +
  geom_jitter(aes(colour = own), 
              size = 2)

ggplot(package_df, aes(x=package, y=amount)) +
  geom_jitter(aes(colour = sos), 
              size = 2)
```

#seeing how choice differed within survey versions. 
```{r}
ggplot(package_df, aes(x=survey_version, y=amount)) +
  geom_dotplot(binaxis = "y", 
               stackdir = "center", 
               dotsize=0.5,
               aes(fill = choice,
                   colour = choice),
               position=position_dodge(0.1)
               #binpositions="all",
               #trim=FALSE
               )+
  geom_hline(yintercept=-25, color = "grey71")+
  geom_hline(yintercept=0, color = "grey71")+
  theme_classic()
#Plot shows that most fishers had similar choices for each survey version. For example, ALL fishers that took survey version1 chose package 2 
```