---
title: "Protest"
author: "BR"
date: "04/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)
library(kableExtra)

master_survey_resp <- read_csv ("master_survey_resp.csv")

```


#Read in protest data
```{r}

protest<-master_survey_resp %>% 
  filter(package_nopackage==0 & wtr_4=="n")

```

#Explore data for trust (all protesting respondents)
```{r}

# Mean trust in different groups for all protestors
protest_summ_all <- protest %>%
  summarize(
    mean_a = round(mean(trust_a), digits = 2),
    sd_a = round(sd(trust_a), digits = 2),
    mean_b = round(mean(trust_b), digits = 2),
    sd_b = round(sd(trust_b), digits = 2),
    mean_c = round(mean(trust_c), digits = 2),
    sd_c = round(sd(trust_c), digits = 2),
    mean_d = round(mean(trust_d), digits = 2),
    sd_d = round(sd(trust_d), digits = 2),
    mean_e = round(mean(trust_e), digits = 2),
    sd_e = round(sd(trust_e), digits = 2),
    mean_f = round(mean(trust_f), digits = 2),
    sd_f = round(sd(trust_f), digits = 2),
    mean_g = round(mean(trust_g, na.rm = TRUE), digits = 2),
    sd_g = round(sd(trust_g,na.rm = TRUE), digits = 2),
    mean_h = round(mean(trust_h), digits = 2),
    sd_h = round(sd(trust_h), digits = 2),
    mean_i = round(mean(trust_i, na.rm = TRUE), digits = 2),
    sd_i = round(sd(trust_i, na.rm = TRUE), digits = 2),
    mean_j = round(mean(trust_j), digits = 2),
    sd_j = round(sd(trust_j), digits = 2),
    mean_k = round(mean(trust_k, na.rm = TRUE), digits = 2),
    sd_k = round(sd(trust_k,na.rm = TRUE), digits = 2),
    mean_l = round(mean(trust_l), digits = 2),
    sd_l = round(sd(trust_l), digits = 2)
  )

# Table for above data
protest_all_table <- kable(t(protest_summ_all)) %>%  # Make a table of protest_summ_all data frame, t transposes table
  kable_styling(full_width = F, position = "center")  # Decrease table width and centers it

protest_all_table



# Mode trust in different groups for all protestors
protest_summ_all2 <- protest %>%
  summarize(
    mode_a = round(mean(trust_a), digits = 2)
  )

```

#Explore data for trust (grouped by access type)
```{r}

# Mean trust in different groups separated into fishing access type
protest_summ_access <- protest %>%
  group_by(access_target_species) %>% # Create subset of data grouped by access, following operations will be performed by group
  summarize(
    mean_a = round(mean(trust_a), digits = 2),
    sd_a = round(sd(trust_a, na.rm = TRUE), digits = 2),
    mean_b = round(mean(trust_b), digits = 2),
    sd_b = round(sd(trust_b), digits = 2),
    mean_c = round(mean(trust_c), digits = 2),
    sd_c = round(sd(trust_c), digits = 2),
    mean_d = round(mean(trust_d), digits = 2),
    sd_d = round(sd(trust_d), digits = 2),
    mean_e = round(mean(trust_e), digits = 2),
    sd_e = round(sd(trust_e), digits = 2),
    mean_f = round(mean(trust_f), digits = 2),
    sd_f = round(sd(trust_f), digits = 2),
    mean_g = round(mean(trust_g, na.rm = TRUE), digits = 2),
    sd_g = round(sd(trust_g, na.rm = TRUE), digits = 2),
    mean_h = round(mean(trust_h), digits = 2),
    sd_h = round(sd(trust_h), digits = 2),
    mean_i = round(mean(trust_i, na.rm = TRUE), digits = 2),
    sd_i = round(sd(trust_i, na.rm = TRUE), digits = 2),
    mean_j = round(mean(trust_j), digits = 2),
    sd_j = round(sd(trust_j), digits = 2),
    mean_k = round(mean(trust_k, na.rm = TRUE), digits = 2),
    sd_k = round(sd(trust_k, na.rm = TRUE), digits = 2),
    mean_l = round(mean(trust_l), digits = 2),
    sd_l = round(sd(trust_l), digits = 2)
  ) # Find mean trust and sd for each group listed in survey question 37 grouped by access type
# Does it make sense to compare these means to means of non-protestors? Do some kinda t-test to see if the difference in means could be a reason why they protest?

# Table for above data
protest_access_table <- kable(protest_summ_access, col.names = c("Access","Other Community Members","sd","Other Communities","sd", "Fishing Association Leaders", "sd", "Fisheries Officers", "sd", "Enforcement","sd", "Consultants", "sd", "Fishery Scientists", "sd", "Local Conservation Groups", "sd", "NGO" ,"sd", "National Govenrment","sd","Local Government","sd", "Private Company","sd")) %>%
  kable_styling(full_width = F, position = "center")  # Decrease table width and centers it

protest_access_table

```

#Explore data for tech use 
```{r}

# General Tech
sum(protest$tech_smartphone, na.rm = TRUE) #19
sum(protest$tech_maps, na.rm = TRUE) #5
sum(protest$tech_socialmedia, na.rm = TRUE) #7
sum(protest$tech_other, na.rm = TRUE) #1
sum(protest$tech_no_tech, na.rm = TRUE) #1

# Fishing Tech
sum(protest$fishtech_vhf, na.rm = TRUE) #4
sum(protest$fishtech_fishfinder, na.rm = TRUE) #3
#survcam doesnt work, but it is 0
sum(protest$fishtech_catchapp, na.rm = TRUE) #0
sum(protest$fishtech_vesseltrack, na.rm = TRUE) #4
sum(protest$fishtech_gps, na.rm = TRUE) #6
sum(protest$fishtech_other, na.rm = TRUE) #5
sum(protest$fishtech_none, na.rm = TRUE) #16
# Majority use a smartphone, but very few use fishing technology

```
 
 note to self: look into packages presented to each of them. maybe they were the least desired ones that BR found?